version: '3.1'
services:

  nginx:
    image: nginx:1.15.7-alpine
    container_name: nginx
    volumes:
      - ./wordpress_data:/var/www/html/:ro
      - ./etc/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
    links:
      - wordpress:php
      - wp-db:db
    ports:
      - 80:80
      - 443:443

  wordpress:
    image: wordpress:5.2.2-php7.2-fpm-alpine
    container_name: wiki
    restart: always
    links:
      - wp-db:mysql
    expose:
      - 9000
    volumes:
      - ./wordpress_data:/var/www/html/
      - ./etc/wordpress/themes:/var/tmp/wp-themes:ro
      - ./etc/wordpress/plugins:/var/tmp/wp-plugins:ro
      - ./etc/wordpress/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ~/.ssh:/root/.ssh
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_CONFIG_EXTRA: |
        /* defaults */
        define('WP_DEFAULT_THEME', 'quads');
        define('WP_POST_REVISIONS', 100);

  wp-db:
    image: mariadb
    container_name: wiki_db
    restart: always
    volumes:
      - ./wiki_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  quads:
    depends_on:
      - quads-db
    build: .
    container_name: quads
    ports:
      - 8080:8080
    environment:
      - MONGODB_IP=quads-db
      - WORDPRESS_IP=wordpress
    volumes:
      - /opt/docker/quads:/opt/quads

  quads-db:
    image: mongo:4.0.4-xenial
    container_name: quads_db
    ports:
      - 27017:27017
    volumes:
      - ./data_db:/data/db

