FROM python:3.10-buster

RUN apt-get install git patch

WORKDIR /opt
RUN git clone https://github.com/redhat-performance/quads

WORKDIR /opt/quads
RUN git checkout flaskapi_v3
RUN python setup.py install

RUN pip install -r tests/requirements.txt
RUN pip install validators

ENV PYTHONPATH=/opt/quads
EXPOSE 5000

ENTRYPOINT ["/opt/quads/container/server/entrypoint.sh"]
