version: '3.1'

networks:
  podman:
    external:
      name: podman

services:

  quads_db:
    image: quay.io/sclorg/postgresql-13-c9s
    container_name: quads_db
    hostname: quads_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USER: postgres
      POSTGRESQL_DATABASE: quads
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        podman:
          ipv4_address: 10.88.0.10

  quads_api:
    depends_on:
      quads_db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Containerfile
    container_name: quads_api
    hostname: quads_api
    ports:
      - 5000:5000
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@quads_db:5432/quads"
    volumes:
      - /var/lib/jenkins/workspace/QUADS-2.1-latest:/opt/quads:z
    networks:
       podman:
         ipv4_address: 10.88.0.11
