FROM quay.io/sclorg/python-311-minimal-c9s

USER 0
RUN microdnf install git patch -y; exit 0

WORKDIR /opt/quads
RUN python setup.py install

RUN pip install -r requirements.txt
RUN pip install -r tests/requirements.txt

ENV PYTHONPATH=/opt/quads
EXPOSE 5000

ENTRYPOINT ["/opt/quads/container/server/entrypoint.sh"]
