---
- gather_facts: False
  name: check for racadm
  vars:
    untouchables: mgmt-foreman.example.com
  hosts: all:!{{untouchables}}
  tasks:

    - name: enable pxe
      local_action: command ipmitool -I lanplus -H {{ inventory_hostname }} -U {{smc_ipmi_user}} -P {{smc_ipmi_pass}} chassis bootdev pxe options=persistent
      ignore_errors: True

# Record when we are finished
    - name: Generate Time of Completion
      local_action: command date +%Y-%m-%d-%H:%M
      register: currentdate

    - name: Print Time of Completion
      debug:
        msg="{{ currentdate.stdout }} , Ansible Playbook for {{ ansible_host }} completed"
